# GitHub Actions workflow for deploying Hugo site to GitHub Pages
name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.147.3'
          extended: true
      
      - name: Install Node.js dependencies
        run: |
          npm ci
      
      - name: Build
        run: |
          hugo --gc --minify --cleanDestinationDir --baseURL https://nessi-dev.github.io/blog/
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: blog.nessi.dev
          enable_jekyll: false
          keep_files: false
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
