# GitHub Actions workflow for deploying Hugo site to GitHub Pages
name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.147.3'
          extended: true
      
      - name: Build
        run: |
          # Clean up
          rm -rf public
          
          # Clean up and prepare directories
          rm -rf themes/
          
          # Clone the theme directly (faster and more reliable than submodules in CI)
          echo "Cloning Ananke theme..."
          git clone --depth 1 --branch v2.0.0 https://github.com/theNewDynamic/gohugo-theme-ananke.git themes/ananke
          
          # Verify theme installation
          echo "Theme directory structure:"
          find themes/ananke -maxdepth 2 -type d | sort
          
          # Install theme dependencies if needed
          if [ -f "themes/ananke/package.json" ]; then
            echo "Installing theme dependencies..."
            cd themes/ananke && npm install && cd ../..
          fi
          
          # Build the site with minimal flags for reliability
          echo "Building site with Hugo..."
          hugo version
          
          # Build with explicit theme path
          THEME_PATH=$(pwd)/themes/ananke
          echo "Using theme from: $THEME_PATH"
          
          # Run Hugo with explicit theme path
          hugo \
            --gc \
            --minify \
            --cleanDestinationDir \
            --baseURL https://blog.nessi.dev/ \
            --themesDir=themes \
            --theme=ananke \
            --path-warnings
          
          # Create necessary files
          echo "Creating deployment files..."
          touch public/.nojekyll
          echo 'blog.nessi.dev' > public/CNAME
          
          # Debug output
          echo "=== Build Complete ==="
          echo "=== Public directory contents ==="
          ls -la public/
          echo -e "\n=== Theme files ==="
          ls -la themes/ananke/static/css/
          echo -e "\n=== CSS Files ==="
          find public -name "*.css" | sort
          echo -e "\n=== Index file (first 20 lines) ==="
          head -n 20 public/index.html
          echo -e "\n=== List of posts ==="
          find public/posts -type f | sort
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public
          clean: true
          clean-exclude: |
            .nojekyll
            CNAME
          commit-message: 'Deploy: Build ${{ github.run_id }}'
          token: ${{ secrets.GITHUB_TOKEN }}
